#!/usr/bin/env bash

export SKETCHYBAR_CONFIG_DIR="/Users/shivraj/dotfiles/sketchybar"
source "$SKETCHYBAR_CONFIG_DIR/variables.sh"

sketchybar --bar height=$BAR_HEIGHT \
  color=$BAR_COLOR \
  corner_radius=$BAR_CORNER_RADIUS \
  y_offset=$BAR_Y_OFFSET \
  margin=$BAR_MARGIN \
  blur_radius=$BAR_BLUR \
  sticky=on \
  position=top \
  shadow=$SHADOW \
  --default updates=when_shown \
  icon.font="$FONT:Bold:13.5" \
  icon.color=$ICON_COLOR \
  icon.padding_left=$PADDINGS \
  icon.padding_right=$PADDINGS \
  label.font="$FONT:Bold:13.0" \
  label.color=$LABEL_COLOR \
  label.padding_left=$PADDINGS \
  label.padding_right=$PADDINGS \
  popup.background.border_width=$BORDER_WIDTH \
  popup.background.corner_radius=$CORNER_RADIUS \
  popup.background.border_color=$POPUP_BORDER_COLOR \
  popup.background.color=$POPUP_BACKGROUND_COLOR \
  popup.background.shadow.drawing=$SHADOW

# Left side
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Right side
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/cpu.sh"

#################### Finalizing Setup ####################

sketchybar --hotload true
sketchybar --update

echo "sketchybar configuration loaded.."
